# Generated by Django 6.0 on 2025-12-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type', models.CharField(choices=[('JOB_NIGHTLY_ETL', 'Job Nightly ETL'), ('JOB_MANUAL_ETL', 'Job Manual ETL'), ('JOB_ML_TRAIN', 'Job ML Training'), ('JOB_ML_PREDICT', 'Job ML Prediction')], max_length=50)),
                ('job_status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_processed', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
