# Generated by Django 6.0 on 2026-01-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_product_price_gt_zero_product_stock_count_gt_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
